version: '3'

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - wordpressdb:/var/www/html
    container_name: nginx
    image: nginx
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - firstnet
    depends_on:
      - wordpress

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    expose:
      - 9000
    volumes:
      - wordpressdb:/var/www/html
    container_name: wordpress
    image: wordpress
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - firstnet
    depends_on:
      - mariadb

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    expose:
      - 3306
    volumes:
      - mariadbdb:/var/lib/mysql
    container_name: mariadb
    image: mariadb
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - firstnet

  website:
    build:
      context: ./requirements/bonus/website
      dockerfile: Dockerfile
    expose:
      - 5000
    volumes:
      - wordpressdb:/var/www/html
    container_name: website
    image: website
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - firstnet

  adminer:
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    expose:
      - 6000
    volumes:
      - adminerdb:/var/www/html
    container_name: adminer
    image: adminer
    restart: unless-stopped
    networks:
      - firstnet

volumes:
  mariadbdb:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/mysql
      o: bind

  wordpressdb:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/wordpress
      o: bind

  adminerdb:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/wordpress
      o: bind

networks:
  firstnet: