version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:443"
    volumes:
      - ./nginx.conf:/etc/nginx/sites-enabled/default
    container_name: nginx-docker
    image: nginx
